### PR TITLE
removed TODO, fixed in a9b62fb

### PR DESCRIPTION
**Pull request by SweBarre**
removed TODO comment that was fixed in a9b62fb

### CODE REVIEW

**Comment by sigsteve** [comment]
@ne0777 can you please look at this one?

**Comment by ne0777** [comment]
Sorry for the delay.  Yes - I mistakenly removed the leading escape for the leading " in \"$masters\" . Thanks Jonas!!  I still think a bunch of the queries in the kubic dashboard need some work.  Enjoying working on this with you all!

**Comment by ne0777** [comment]
Git removed my "\"s from the above comment btw.

**Comment by ne0777** [comment]
Agh!!  "backslashes"

**Pull request merged**
